### PR TITLE
digital-inverter-openlane: add OpenLane PDK env vars

### PR DESCRIPTION
**Pull request by proppy**
Since https://github.com/The-OpenROAD-Project/OpenLane/pull/1251 it seems that the following environment are now required to be set explicitly:
```
PDK=sky130A
STD_CELL_LIBRARY=sky130_fd_sc_hd
STD_CELL_LIBRARY_OPT=sky130_fd_sc_hd
```

### CODE REVIEW

**Comment by proppy** [comment]
@donn can you review?

**Comment by donn** [comment]
`PDK=sky130A` does have to be set explicitly, but the rest do have default values. Nothing wrong with being prudent though.

**Review by donn — APPROVED** [review]

**Comment by proppy** [comment]
Yep, without setting it I get:
```
[INFO]: Using configuration in 'config.tcl'...
[INFO]: PDK Root: /content/conda-env/share/pdk
[ERROR]: PDK is not specified.
```

**Comment by proppy** [comment]
But if I only set `PDK` I get a different error:
```
OpenLane 57f3f21d6e1d0403a88d7a7973f7447597aae160
All rights reserved. (c) 2020-2022 Efabless Corporation and contributors.
Available under the Apache License, version 2.0. See the LICENSE file for more details.

[INFO]: Using configuration in 'config.tcl'...
[INFO]: PDK Root: /content/conda-env/share/pdk
[INFO]: Process Design Kit: sky130A
no such variable
    (read trace on "::env(STD_CELL_LIBRARY)")
    invoked from within
"set ::env(TECH_LEF) "$::env(PDK_ROOT)/$::env(PDK)/libs.ref/$::env(STD_CELL_LIBRARY)/techlef/$::env(STD_CELL_LIBRARY)__nom.tlef""
    (file "/content/conda-env/share/pdk/sky130A/libs.tech/openlane/config.tcl" line 15)
    invoked from within
"source $pdk_config"
    (procedure "prep" line 142)
    invoked from within
"prep {*}$args"
    (procedure "run_non_interactive_mode" line 12)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
    if { [info exists arg_values(-file)] } {
        run_file [file nor..."
    (file "/content/OpenLane/flow.tcl" line 401)
```
so I assumed `STD_CELL_LIBRARY` as also required.

**Comment by proppy** [comment]
should I file an issue on the OpenLane side about providing defaults for those?

**Comment by proppy** [comment]
and not setting `STD_CELL_LIBRARY_OPT` produces:
```
OpenLane 57f3f21d6e1d0403a88d7a7973f7447597aae160
All rights reserved. (c) 2020-2022 Efabless Corporation and contributors.
Available under the Apache License, version 2.0. See the LICENSE file for more details.

[INFO]: Using configuration in 'config.tcl'...
[INFO]: PDK Root: /content/conda-env/share/pdk
[INFO]: Process Design Kit: sky130A
no such variable
    (read trace on "::env(STD_CELL_LIBRARY_OPT)")
    invoked from within
"set ::env(TECH_LEF_OPT) "$::env(PDK_ROOT)/$::env(PDK)/libs.ref/$::env(STD_CELL_LIBRARY_OPT)/techlef/$::env(STD_CELL_LIBRARY_OPT)__nom.tlef""
    (file "/content/conda-env/share/pdk/sky130A/libs.tech/openlane/config.tcl" line 33)
    invoked from within
"source $pdk_config"
    (procedure "prep" line 142)
    invoked from within
"prep {*}$args"
    (procedure "run_non_interactive_mode" line 12)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
    if { [info exists arg_values(-file)] } {
        run_file [file nor..."
    (file "/content/OpenLane/flow.tcl" line 401)
```

**Comment by donn** [comment]
If you see that, then the version of OpenLane and the PDK being used are mismatched- when OpenLane started requiring `PDK`, `open_pdks` was updated to add defaults for these values

**Comment by proppy** [comment]
Ah interesting, thanks for the pointer!

tThe notebook is using the latest packaged version OpenPDKS:
```
  + open_pdks.sky130a   1.0.323_0_g6003ab3  20220811_123320       litex-hub/noarch       125MB
``` 
but the package might be missing the file where those default are defined, I'll investigate this on the https://github.com/hdl/conda-eda side, thanks for the review!

**Comment by donn** [comment]
Btw, just to verify- you are using https://github.com/efabless/open_pdks/, right? That's the one I use with OpenLane

**Comment by proppy** [comment]
@donn oh, I didn't realize there was a fork! Let's discuss this in https://github.com/hdl/conda-eda/issues/235.

**Pull request merged**
