### PR TITLE
github/workflows: add ci

### PR DESCRIPTION
**Pull request by proppy**
- lint notebooks with https://github.com/nbQA-dev/nbQA
- run notebooks with https://github.com/treebeardtech/nbmake
- exclude analog and xls-workshop #56 #57 

TEST=https://github.com/proppy/silicon-notebooks/actions/runs/4045046825
TEST=https://github.com/proppy/silicon-notebooks/actions/runs/4045046823

### CODE REVIEW

**Comment by proppy** [comment]
@bmurmann you might also be interested in this, as it allows to do some validation of change to the jupyter notebooks you maintain.

**Review by mithro — APPROVED** [review]
LGTM.

**Comment by proppy** [comment]
@pgielda @mgielda @PiotrZierhoffer @umarcor also curious if you have some feedback on the methodology used here for doing CI on jupyter notebooks.

**Pull request merged**
