### PR TITLE
Japanese translation for tape-out section.

### PR DESCRIPTION
**Pull request by shige-compit**
Japanese translation for [the PR: "add tapeout section"](https://github.com/chipsalliance/silicon-notebooks/pull/35/commits/f258bab5c1fa7a03b200020fa1ee245e71174faf).

### CODE REVIEW

**Comment by shige-compit** [comment]
@t-sasatani Could you double check the Japanese, when you have time?
https://colab.sandbox.google.com/github/shige-compit/silicon-notebooks/blob/main/xls-workshop-openlane-ja.ipynb

**Comment by shige-compit** [comment]
Added translation for Pipeline assignment as well.
Note: It may note reflect recent discussions on [the pull request](https://github.com/chipsalliance/silicon-notebooks/pull/36#issuecomment-1354359192).

**Comment by t-sasatani** [comment]
Looks good! (although I'm not sure about Japanese terminologies)
We should delete the first tapeout markdown block because there's the same block later. This applies to the original English version too. @proppy

**Comment by shige-compit** [comment]
> We should delete the first tapeout markdown block because there's the same block later. This applies to the original English notebook too. @proppy

Thanks! I removed the duplicated part. I'd defer to @proppy for Eng version.

**Pull request merged**
