### PR TITLE
xls: add workshop notebook

### PR DESCRIPTION
**Pull request by proppy**
- use micromamba & OpenLane condo packages
- split each of the openlane steps
- add 3D gds viewer
- add caravel harness outro

TEST=https://colab.research.google.com/github/proppy/silicon-notebooks/blob/workshop/xls-workshop-openlane.ipynb
TEST=https://colab.research.google.com/github/proppy/silicon-notebooks/blob/workshop/xls-workshop-openlane-ja.ipynb

Replace #20

### CODE REVIEW

**Comment by proppy** [comment]
@t-sasatani @shige-compit, I'd like to publish the notebook we used for the workshop.

Can you review?

**Comment by shige-compit** [comment]
I confirmed that both notebooks can work as expected.

### Feedback:
An error/warning message "不明な理由により、セッションがクラッシュしました(Session is crashed due to unknown reason.)" shown after Kernel restart may make learners surprised and anxious. I understand it's inevitable to get WARNING when we restart the kernel. Should we provide a note that the error/warning message is expected and no problem?

Pop-up for error/warning
image
app.log details.
image

 ### Minor correction:
For the Japanese notebook, サインオフ part
`- 出力: ファウンドリの[DRCルール](https://en.wikipedia.org/wiki/Design_rule_checking)検証済みで製造に出せる物理レイアウト ([GDSII](https://en.wikipedia.org/wiki/GDSII))`
is not rendered appropriately on Colab (interestingly, it's no problem on GitHub preview) since there is no space after the link. 
image
The following should be safer.
`- 出力: ファウンドリの[DRCルール](https://en.wikipedia.org/wiki/Design_rule_checking), 検証済みで製造に出せる物理レイアウト ([GDSII](https://en.wikipedia.org/wiki/GDSII))`

**Comment by proppy** [comment]
> An error/warning message "不明な理由により、セッションがクラッシュしました(Session is crashed due to unknown reason.)" shown after Kernel restart may make learners surprised and anxious.

Good point we do have a note about the kernel restarting but we don't say anything about the warning message.

We should actually be able to get rid of the restart by overriding path similar to what we do in the digital-inverter colab: https://github.com/chipsalliance/silicon-notebooks/blob/main/digital-inverter-openlane.ipynb

**Comment by proppy** [comment]
@shige-compit 

> An error/warning message "不明な理由により、セッションがクラッシュしました(Session is crashed due to unknown reason.)" shown after Kernel restart may make learners surprised and anxious. I understand it's inevitable to get WARNING when we restart the kernel. Should we provide a note that the error/warning message is expected and no problem?

Removed the need to restart the notebook, let me know if that's better.

**Comment by shige-compit** [comment]
I confirmed the update notebooks can work without any issues and provide a better experience. LGTM.

**Comment by proppy** [comment]
> For the Japanese notebook, サインオフ part
- 出力: ファウンドリの[DRCルール](https://en.wikipedia.org/wiki/Design_rule_checking)検証済みで製造に出せる物理レイアウト ([GDSII](https://en.wikipedia.org/wiki/GDSII))

@shige-compit I think this still need to be corrected.

**Comment by shige-compit** [comment]
Ah, yeah. Sorry, I totally forgot the minor correction I myself pointed out. Good to know you haven't forgotten about it.

**Comment by proppy** [comment]
> Ah, yeah. Sorry, I totally forgot the minor correction I myself pointed out. Good to know you haven't forgotten about it.

@shige-compit fixed with 7fde676

**Comment by shige-compit** [comment]
Thanks. I confirmed it appropriately rendered on Colab as well.

**Comment by proppy** [comment]
@shige-compit added an assignement in befe599 [(updated colab)](https://colab.research.google.com/github/proppy/silicon-notebooks/blob/workshop/xls-workshop-openlane.ipynb#scrollTo=zEET8HjMKcbj), let me know what you think.

**Comment by shige-compit** [comment]
I made a Japanese version based on your update. 
https://gist.github.com/shige-compit/7a1c405d9e26929811a04ec31412f628

I felt "Observe changes in the metric/layout" a little ambiguous. Maybe "Observe the metrics/layout and compare it with adder's one" would be clearer. I used the explanation for my Japanese translation.

**Comment by proppy** [comment]
> I made a Japanese version based on your update.
https://gist.github.com/shige-compit/7a1c405d9e26929811a04ec31412f628
 
Added in 6866272

> I felt "Observe changes in the metric/layout" a little ambiguous. Maybe "Observe the metrics/layout and compare it with adder's one" would be clearer. I used the explanation for my Japanese translation.

Added extra instructions w/ 8fabea1

**Comment by proppy** [comment]
@shige-compit as we noted during the last workshop: fixed the density in the assignement so that it fails the fist time it runs 537f8e7.

**Comment by proppy** [comment]
Merging since I believe more most of the feedbacks have been addressed.

**Pull request merged**
