### PR TITLE
gf180mcu: digital inverter notebook

### PR DESCRIPTION
**Pull request by proppy**
image

TEST=https://colab.research.google.com/github/proppy/silicon-notebooks/blob/gf180mcu/digital-inverter-openlane-gf180mcu.ipynb

@Cra2yPierr0t @mattvenn @donn can you give it a try?

### CODE REVIEW

**Comment by proppy** [comment]
@tcal-x @ShvetankPrakash this notebook should be more solid than the ones from gist.github.com, as it relies on the packaged version of OpenLane.

Let me know if it works for you.

**Comment by tcal-x** [comment]
@proppy  Yes this one is much better; it fixes the "openlane" vs "OpenLane" path issue, and it's nice that it doesn't need a kernel restart, so "play all" goes all the way through.

How does the 'runs' variable get set?

**Comment by tcal-x** [comment]
@shvetankprakash try this out

**Comment by proppy** [comment]
> How does the 'runs' variable get set?

by default openlane uses `runs` but you can specific a different directory using `-run_path` https://openlane.readthedocs.io/en/latest/reference/cli.html#:~:text=of%20that%20run.-,%2Drun_path%20%3Cpath%3E,-(Optional)

under by default openlane create a subdirectory against the current datetime, but you can override with `-tag` https://openlane.readthedocs.io/en/latest/reference/cli.html#:~:text=expose%20KEY1%2CKEY2-,%2Dtag%20%3Cname%3E,-(Optional)

**Comment by donn** [comment]
@proppy BTW, if you notice any of these variables could use better defaults/better names, just drop me an email.

**Comment by proppy** [comment]
@donn do you prefer separate issue for each suggestion? or one that summarize all of them?

**Comment by donn** [comment]
@proppy One issue should be fine.

**Comment by ShvetankPrakash** [comment]
@proppy @tcal-x will check this out, thanks for the reference!

**Comment by proppy** [comment]
@tcal-x @ShvetankPrakash let me know if you think it's good enough to merge.

**Comment by tcal-x** [comment]
@proppy I think it's great, especially now that it completes with just a single "run all".   I timed it at 4 minutes end to end.

The only very minor nit that I would mention is the progress bars for the initial download/install tasks result in a lot of scrolling (many lines in the output).  Might be worth seeing if you can turn off the progress bar.

**Comment by ShvetankPrakash** [comment]
I also timed it at 4 min @tcal-x . Only thing I may mention @proppy is that it would be nice to know what some of the params in the `config.json` mean exactly. Most of them are intuitive like die area, target density, design name, clock tree, etc. But a couple of them were not intuitive (this might just be for me and obvious for others, though) so a pointer to their defs might be nice to include. It might not be necessary but just a thought I wanted to include. Looks really great overall!

**Comment by proppy** [comment]
@tcal-x 
> The only very minor nit that I would mention is the progress bars for the initial download/install tasks result in a lot of scrolling (many lines in the output)

a03b640

@ShvetankPrakash 
> Only thing I may mention @proppy is that it would be nice to know what some of the params in the config.json mean exactly

c18651f

PTAL

**Comment by tcal-x** [comment]
Looks great!

**Review by tcal-x — APPROVED** [review]
LGTM!

**Pull request merged**
