### PR TITLE
xls-workshop-openlane: add diy section

### PR DESCRIPTION
**Pull request by proppy**
- add diy section for people to work on their own design

TEST=https://colab.research.google.com/github/proppy/silicon-notebooks/blob/workshop-diy/xls-workshop-openlane.ipynb
TEST=https://colab.research.google.com/github/proppy/silicon-notebooks/blob/workshop-diy/xls-workshop-openlane-ja.ipynb

@shige-compit @t-sasatani do you think we need something like this?

### CODE REVIEW

**Comment by t-sasatani** [comment]
I think it'll be better to have that (although we can probably ask re-using or copying the multiplier code blocks)

**Comment by proppy** [comment]
@t-sasatani what would be the Japanese equivalent? 自由研究?

**Comment by t-sasatani** [comment]
I think just English is ok for that part because there's no real equivalent word (also 自由研究 makes me feel like I need to submit a report!)

**Comment by proppy** [comment]
rebased and added japanese equivalent.

**Comment by proppy** [comment]
@shige-compit reviewed offline and suggested the rewording

**Pull request merged**
